export const ROUTES = {
    HOME: "/",
    BRAND_OWNERS: "/brand-owners",
    PACKAGING_CONVERTERS: "/packaging-converters",
    CONATCT_US: "/contact-us",
    ABOUT: "/about",
    SERVICES: "/services",
    BLOG: "/blog/",
    OUR_WORKS: "/work-page/",
    GALLERY: "/gallery",
    APP_and_Business: "/application-and-businness-development",
    BUSINESS_REMODELING: "/business-remodeling",
    CARRERS: "/careers",
    MANAGEMENT_AND_ASSISTANCE: "/management-and-assistance",
    RESOURCING: "/resourcing",
    SOURCING_EXCELLENCE: "/sourcing-excellence",
    OPERATIONAL_EXCELLENCE: "/operational-excellence",
    VALUE_IMPROVEMENT: "/value-improvement",
    PACKAGING_INNOVATION: "/packaging-innovation",
    SUSTAINABLE_SOLUTION: "/sustainable-solution",
}

export const ADMIN_ROUTES = {
    LOGIN: "/admin",
    BLOGS: "/admin/blogs",
    BLOGS_ID: "/admin/blogs/",
    BLOGS_CREATE: "/admin/blogs/create",
    BLOGS_LAYOUT_1: "/admin/blogs/layout1",
    BLOGS_EDIT_LAYOUT_1: "/admin/blogs/edit/layout1/",
    BLOGS_LAYOUT_2: "/admin/blogs/layout2",
    BLOGS_EDIT_LAYOUT_2: "/admin/blogs/edit/layout2/",
    BLOGS_LAYOUT_3: "/admin/blogs/layout3",
    BLOGS_EDIT_LAYOUT_3: "/admin/blogs/edit/layout3/",

    OUR_WORKS: "/admin/our-works",
    OUR_WORKS_EDIT: "/admin/our-works/edit/our-work/",
    NEW_WORK: "/admin/our-works/new-work",
}